name = "Birb"
author = "sollmann"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc72469da3f69bca99f1a73af2a934c2ef2e5d44cd222969783add2b1e6fc0bb"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
datapack-folder = "datapacks"
