name = "Birb"
author = "sollmann"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "936de0906e5b713db62075088876ac12255fc8babf6943a8043087e26c371082"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
datapack-folder = "datapacks"
